### PR TITLE
Added province options to Google geocoder

### PR DESCRIPTION
**Pull request by mzino**

### CODE REVIEW

**Comment by nchaulet** [comment]
Province is not adminstrative_level_2 in all countries and node-geocoder is used in many country.

I thinks it could be more interesting to have an `administrative_levels` key in the returned geocoding object with all level.

What do you think?

**Comment by mzino** [comment]
Something like this?

**Comment by nchaulet** [comment]
yes seems good for me :+1:

**Comment by nchaulet** [comment]
thanks for the pull request

**Comment by mzino** [comment]
Thank you for the great module!
It'd be great to have the latest updates in the npm package, if you have the time.

**Comment by nchaulet** [comment]
v2.23.0

**Pull request merged**
