### PR TITLE
Add support for place_id and formatted_address

### PR DESCRIPTION
**Pull request by jtemps**
Adds options to include place_id and/or formatted_address when using google as the geocoder

### CODE REVIEW

**Comment by nchaulet** [comment]
Thanks for yours PR I thinks the two extra field could be in geocoder without options.
Could you use `formattedAddress`  and `googlePlaceId`for the field name ?

**Comment by nchaulet** [comment]
Maybe `googlePlaceId` could be in an extra key
an examle 
```
{
latitude: 1
longitude: 1
formattedAddress: 'qdqsdsqd',
extra: {
     googlePlaceId
}
}
```

**Comment by jtemps** [comment]
Sure thing! Made the requested changes

**Comment by nchaulet** [comment]
Thanks could you fix the test ? and I merge this :)

**Comment by jtemps** [comment]
Was just doing that - sorry! Fixed tests

**Comment by nchaulet** [comment]
v2.20.0 on npm

**Pull request merged**
