### PR TITLE
Yandex: return float lat/lng instead of string

### PR DESCRIPTION
**Pull request by yosiat**
The latitude and longitude from Yandex geocoding result are string,
while I expected to get float numbers (like google geocoding result).

### CODE REVIEW

**Comment by yosiat** [comment]
@nchaulet can you please give a look?

**Comment by evgenybron** [comment]
we are facing the same problem, @nchaulet  can you please accept the  raised pr?
thanks in advance.

**Comment by nchaulet** [comment]
Hi i am just coming back from vacation I will take a look to that tomorrow
morning (EST)
-- 
Nicolas Chaulet (*Développeur Web)*

*Contact :*

    tél : +1 514 794 1990
    mail : n.chaulet@gmail.com
    twitter : @n_chaulet <https://twitter.com/n_chaulet>

**Comment by nchaulet** [comment]
Fixed in 3.20.1 thanks for the PR and sorry for the long delay

**Comment by yosiat** [comment]
@nchaulet thank you!

**Pull request merged**
